---
apiVersion: v1
kind: Service
metadata:
  name: f5-f5-served-ns-{{ .ns }}-{{ .Replica }}
  labels:
    app: f5-f5-served-ns-{{ .ns }}-{{ .Replica }}
    cis.f5.com/as3-tenant: f5-served-ns-{{ .ns }}
    cis.f5.com/as3-app: f5-f5-served-ns-{{ .ns }}-{{ .Replica }}
    cis.f5.com/as3-pool: web_pool
spec:
  ports:
  - name: f5-f5-served-ns-{{ .ns }}-{{ .Replica }}
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: f5-f5-served-ns-{{ .ns }}-{{ .Replica }}
